# This section is for your AAP Gateway host(s)
# -----------------------------------------------------
[automationgateway]
aap-gw1.example.org ansible_host=10.0.15.199
aap-gw2.example.org ansible_host=10.0.5.255

# This section is for your AAP Controller host(s)
# -----------------------------------------------------
[automationcontroller]
aap-ac2.example.org ansible_host=10.0.12.30
aap-ac1.example.org ansible_host=10.0.7.139

# This section is for your AAP Execution host(s)
# -----------------------------------------------------
[execution_nodes]
# hop1.example.org receptor_type='hop'
# exec1.example.org
# exec2.example.org

# This section is for your AAP Automation Hub host(s)
# -----------------------------------------------------
[automationhub]
aap-hub1.example.org ansible_host=10.0.0.43
aap-hub2.example.org ansible_host=10.0.15.5

# This section is for your AAP EDA Controller host(s)
# -----------------------------------------------------
[automationeda]
aap-eda1.example.org ansible_host=10.0.9.95
aap-eda2.example.org ansible_host=10.0.13.87

[redis]
aap-gw1.example.org ansible_host=10.0.15.199
aap-hub1.example.org ansible_host=10.0.0.43
aap-eda1.example.org ansible_host=10.0.9.95
aap-eda2.example.org ansible_host=10.0.13.87
aap-hub2.example.org ansible_host=10.0.15.5
aap-gw2.example.org ansible_host=10.0.5.255

[database]
aap-db1.example.org ansible_host=10.0.7.177

[lab-lb]
jumpserver ansible_host=3.24.28.76 ansible_ssh_common_args=''

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa ec2-user@3.24.28.76" -o StrictHostKeyChecking=no'
hub_shared_data_path=fs-036c93ccb20eec701.efs.ap-southeast-2.amazonaws.com:/
